-- Chores App — Seed example data (GUTTED post-ship; see ev-59).
--
-- This migration ORIGINALLY seeded three placeholder kids (Kid One/Two/Three,
-- users kid1/kid2/kid3) plus their demo zones (Bathroom / Bedroom) and chores.
-- That placeholder household was visible clutter no other app shipped and kept
-- chores out of the ev-52 empty-state hero. It has been REMOVED so a FRESH
-- install seeds NO chores data at all — a household starts empty and adds its
-- own kids/zones/chores.
--
-- The migrator tracks applied files by FILENAME (public.app_migrations), so
-- editing this already-applied file does NOT re-run it or de-seed existing
-- boxes. Its upgrade companion is 007_remove_placeholder_kids.sql, an
-- idempotent forward-only cleanup that removes the placeholder seed from
-- already-upgraded installs — but ONLY where it is still an untouched
-- placeholder (an adopted starter household is left intact).
--
-- Intentionally a no-op on fresh installs. Do not re-add seed data here.
